/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as MeuPainelRouteImport } from './routes/meu-painel'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPainelRoute = MeuPainelRouteImport.update({
  id: '/meu-painel',
  path: '/meu-painel',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/meu-painel': typeof MeuPainelRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/meu-painel': typeof MeuPainelRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof CampanhasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/insights': typeof InsightsRoute
  '/meu-painel': typeof MeuPainelRoute
  '/relatorios': typeof RelatoriosRoute
  '/setup': typeof SetupRoute
  '/clientes/$id': typeof ClientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campanhas'
    | '/clientes'
    | '/financeiro'
    | '/insights'
    | '/meu-painel'
    | '/relatorios'
    | '/setup'
    | '/clientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campanhas'
    | '/clientes'
    | '/financeiro'
    | '/insights'
    | '/meu-painel'
    | '/relatorios'
    | '/setup'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/campanhas'
    | '/clientes'
    | '/financeiro'
    | '/insights'
    | '/meu-painel'
    | '/relatorios'
    | '/setup'
    | '/clientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CampanhasRoute: typeof CampanhasRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  InsightsRoute: typeof InsightsRoute
  MeuPainelRoute: typeof MeuPainelRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-painel': {
      id: '/meu-painel'
      path: '/meu-painel'
      fullPath: '/meu-painel'
      preLoaderRoute: typeof MeuPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CampanhasRoute: CampanhasRoute,
  ClientesRoute: ClientesRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  InsightsRoute: InsightsRoute,
  MeuPainelRoute: MeuPainelRoute,
  RelatoriosRoute: RelatoriosRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
